### ISSUE TITLE
Suggest to loosen the dependency on catalyst

### ISSUE THREAD

**Issue by Agnes-U** [kadirnar/semantic-segmentation-pytorch#8]
Dear developers, 

Your project semantic-segmentation-pytorch requires "catalyst==22.2.1" in its dependency. After analyzing the source code, we found that the following versions of catalyst can also be suitable without affecting your project, i.e., catalyst 22.02rc0, 22.02, 22.2rc0, 22.2, 22.02.1. Therefore, we suggest to loosen the dependency on catalyst from "catalyst==22.2.1" to "catalyst>=22.2,<=22.2.1" to avoid any possible conflict for importing more packages or for downstream projects that may use ddos_script. 

May I pull a request to further loosen the dependency on catalyst?

By the way, could you please tell us whether such dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

<br />

----

Details: 

Your project (commit id: 5468f80dc70ed4eb5d66207fb88c2a08db448d49) directly uses 2 APIs from package catalyst.

```
catalyst.utils.misc.set_global_seed, catalyst.utils.torch.prepare_cudnn
```

Beginning fromwhich, 4 functions are then indirectly called, including 0 catalyst's internal APIs and 4 outsider APIs as follows:
```
[/kadirnar/semantic-segmentation-pytorch]
+--catalyst.utils.misc.set_global_seed
|      +--random.seed
|      +--numpy.random.seed
|      +--torch_xla.core.xla_model.set_rng_state
+--catalyst.utils.torch.prepare_cudnn
|      +--os.environ.get
```

Since all these functions have not been changed between any version for package "catalyst" from [22.02rc0, 22.02, 22.2rc0, 22.2, 22.02.1] and 22.2.1. Therefore, we believe it is safe to loosen the corresponding dependency.

**Comment by kadirnar** [comment]
Hello @Agnes-U ,

 That would be great. If you open a Pull Request I can accept it.

**Comment by Agnes-U** [comment]
Thank you for your reply! I found that this modification has been updated before, [here](https://github.com/Agnes-U/semantic-segmentation-pytorch/blob/main/requirements.txt), thanks :)
